### ISSUE TITLE
Allow writer to be set manually on an existing indexer

### ISSUE THREAD

**Issue by jrochkind** [traject/traject#103]
indexer.writer = some_writer

Right now, #process insists on instantiating a writer according to configuration, and will overwrite something you set manually as above. https://github.com/traject/traject/blob/master/lib/traject/indexer.rb#L395

Should it allow you to set a writer in code instead?  I think probably. 

One issue is whether you can call #process more than once. In general, existing writers are use-once-only, as they do things in #close that aren't neccesarily idempotent and don't neccesarily reset their internal state after a #close.  I don't think traject _stops_ you from calling #process more than once either, it doesn't raise if you do, it just might not work.  This could be rectified in one direction or another, it's sort of an open issue. (Probably the writer itself should raise if it gets a `put` called after `close`, and it can't handle that). 

I think maybe that was why process insists on instantiating a new writer, I was thinking of leading toward being able to call #process twice in cases where the writer (and reader?) would need to be reinstantiated to do so. But this wasn't done anyway. 

Any thoughts @billdueber ?

**Comment by billdueber** [comment]
+1 to this -- there are plenty of use cases where you might want to instantiate a writer in code (the most obvious being where you want to set up a database select as your input stream). 

Right now, I worry that `#process` has too much going on in general, and that we're not doing it right:
* It takes an IO stream, which it then internally turns into a reader. Readers should create themselves based on the settings, esp. since some useful readers don't take an input stream as such. I'd actually prefer if the only restriction on a reader is that it respond to `#each`.
* Ditto with writer -- `#process` should probably just verify that a valid reader (something that `#respond_to? :each` and a valid writer (responds to ... `#put`? `#write`? `#put` is nice, but it doesn't map onto the IO API at all)

I don't think it makes sense to call `#process` more than once -- that's a weird-ass use case, and it's not unreasonable to make the user clean up the reader/writer in-between. 

I'm gonna make a branch and play with this after lunch.

**Comment by jcoyne** [comment]
:+1: I also have this use case.
