### ISSUE TITLE
Traject silently fails on bad xml

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#127]
For example spaces prior to `<?xml`.  Perhaps it could die with `FATAL: Invalid xml.`

**Comment by jrochkind** [comment]
I assume this about MarcXML, using the Traject::MarcReader, which uses `MARC::XMLReader.new` from the ruby-marc gem, which also by default is told to use `MARC::XMLReader.best_available` "parser". 

https://github.com/ruby-marc/ruby-marc/blob/8321b55208486040923e7fcf84d4c0bb2b1c632a/lib/marc/xmlreader.rb#L97

Which can depend on platform and whether nokogiri is available, but is _probably_ nokogiri under context reported here?  Would have to reproduce to be sure. 

The behavior may depend on what parser is being used. I think we might have to change this in ruby-marc to (optionally?) raise on bad XML, instead of apparently silently ignoring. Don't think there's any good way for traject to work around it otherwise.

**Comment by billdueber** [comment]
The MARC-XML reader in ruby-marc is kind of a mess across the board -- I'm gonna try to find some time to look at it this month and make it a little less insane.

**Comment by adjam** [comment]
It happens with Nokogiri (at least),  I've created a [PR for `ruby-marc`](/ruby-marc/ruby-marc/pull/56)

**Comment by jrochkind** [comment]
Sweet thanks @adjam!  I'm going to close the issue here, once fixed in ruby-marc/ruby-marc#56, traject will behave as expected I believe.

**Comment by jrochkind** [comment]
We're gonna need someone to merge and release in ruby-marc...  I have privs, but @adjam , do you want commit/release rights to ruby-marc? Cause I believe I have the power to give em to you...

**Comment by adjam** [comment]
Sure, I can handle that.  Dunno the overall process though.  Assuming I merge the PR, then I'd update `Changes` on master and do a release?  Is there a process for publishing to rubygems?
