### ISSUE TITLE
Eliminate use of deprecated 'URI.regexp' method

### ISSUE THREAD

**Issue by billdueber** [traject/traject#136]
...which throws warnings all over the place during testing. 

Would be a good one for a new contributor to try to pick up ...

**Comment by jrochkind** [comment]
Can anyone find the the commit that deprecates this and explains why? It is convenient. 

It looks like all we're using the regexp for is argument checking to ensure something expected to be a URI really looks like one. https://github.com/traject/traject/blob/0914a396306c2489a7e270f33793ca76665f8f19/lib/traject/solr_json_writer.rb#L239-L252  @billdueber do you anticipate simply removing these sanity checks (letting it fail naturally later if it isn't reachable, instead of failing early with clear error message), or doing the check through some other means?
