### ISSUE TITLE
Including Macros in config files seems awkward

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#141]
in my traject config I've added this:

```ruby
require_relative 'macros/mods'
require_relative 'macros/xml'
Traject::Indexer.include Macros::Xml
Traject::Indexer.include Macros::Mods
```

Is this the best way to include functionality?

**Comment by jrochkind** [comment]
Yes, it is right now, you've got it. 

What I'd do is I'd have more than one config file for traject, as you can, they will be run in order. And I'd make the first one just those includes. So your actual traject call would look like:

    traject -c mods_setup.rb -c actual_config.rb

And you can re-use that mods_setup.rb between different actual_config.rb. You could also write a simple wrapper script (ruby or bash) that just insists on putting `-c mods_setup.rb` at the beginning of the arg list for you. 

You could additionally give traject load paths to look for config files on with the `-I` flag, so you wouldn't need to spell out the complete path to the hypothetical `mods_setup.rb`, but I'm not totally sure how useful that is at making the command line more legible or consise.   Or of course you can always adjust the `$LOAD_PATH` in a config file so once you're in there you can avoid the `require_relative` and just use standard require. 

Another option, if you have a Gemfile and run as `bundle exec traject`, then all your gems will already be on the load path, so you could just `-c mods_setup.rb` if one of the gems has a `mods_setup.rb` at `./lib` (I _think_ this will work, not sure I've ever tried it but I intended it). And bundle exec will mean you don't need those `require_relative`s, you can do ordinary `require` to gem dependencies. 

Those are basically your options now. If you can think of a better API, feel free to suggest it! But you're going to have to tell traject about the custom stuff _somewhere_, so I guess we could make it one line in a config file instead of two at best.   

Hypothetically, I am in favor of seeing built-in XML stuff that you might trigger with an -X flag, which would _not_ include the MARC macros etc.  But that would take more internal refactoring, and I'd still want to support this kind of custom macro anyway, and want to make it straightforward. I'm hoping no internal refactoring is needed to make custom macros convenient. 

Thoughts?

**Comment by jrochkind** [comment]
Oh actually one tweak. With what you've done, I would not do:

     Traject::Indexer.include Macros::Xml

But rather just:

     include Macros::Xml

The 'self' context in a config file is an indexer, just add it to that indexer, slightly more concise. 

And actually one more useful tool. You can put in a config file:

    load_config_file absolute_or_relative_path

So you could have your hypothetical `actual_config.rb` just do that at the top, as sort of a way of one config expressing dependency on another (eg actual_config dependency on mods_setup). 

Right now `load_config_file` has to be an absolute or relative paths, it doesn't use $LOAD_PATH, but we could make it do so, as an option or another method or whatever. 

Hopefully you can put together something sensible from these various tools and options?

**Comment by jrochkind** [comment]
For more info and ideas, see: https://github.com/traject/traject/blob/master/doc/extending.md

**Comment by jrochkind** [comment]
Curious to hear what pattern end up using, if you want to share. There are a lot of ways to do this, would be good to record which ended up working.

**Comment by jcoyne** [comment]
Sure, the code kicks off here: 
https://github.com/sul-dlss/dlme/blob/a82d925fcc93789dd3d35e0bc7488cee6421586e/bin/fetch_and_import#L18-L39

Then used the extend approach here:
https://github.com/sul-dlss/dlme/blob/a82d925fcc93789dd3d35e0bc7488cee6421586e/lib/traject/tei_config.rb

**Comment by jrochkind** [comment]
Thanks @jcoyne. If you're doing programmatic use of the indexer like that, you could leave any reference to mods out of the config file, and do it in your fetch_and_import script:

~~~ruby
def process_mods(identifier, mods)
  indexer = Traject::Indexer.new('identifier' => identifier, 'exhibit_slug' => Settings.import.slug)
  indexer.extend Macros::Xml
  indexer.extend Macros::Tei
  indexer.load_config_file('lib/traject/mods_config.rb')
  indexer.process(mods)
end
~~~

You could of course make one module that itself includes both Macros::XML and Macros::TEI, so you only have to extend one thing. 

It's all up to you, a bunch of ways to do it, pretty much all just plain ruby.

**Comment by jrochkind** [comment]
Or I suppose you could even make a custom-subclass of Traject::Indexer that does nothing but `include` those modules, and just use that. JCoynesTeiIndexer or whatever. Many options in ruby to get a module included into a class or specific instance, you can use any of them, it's just ruby.
