### ISSUE TITLE
There should be a logger in the LineWriter

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#201]
So that I'm able to write errors somewhere without having to instantiate a logger that is separate from the one in the indexer.

**Comment by jrochkind** [comment]
I think maybe you should have access to the current logger being used by the indexer -- maybe in `settings["logger"]` or `context.logger`.  It's been a while since I've looked at this, looking at code trying to refresh my memory. 

Is access to the current logger what you are looking for, or do you want/need a logger particular to the writer? 

If I'm misunderstanding, can you say more about your use case, where the code is that needs to log, and where you want/expect it to log?

**Comment by jcoyne** [comment]
You're right `context.logger` was what I needed.

**Comment by jrochkind** [comment]
Awesome, thanks!
